// Thin wrapper that falls back to mock data when running outside Electron (browser preview)
const isElectron = typeof window !== 'undefined' && !!window.api

const mock = {
  projects: [],
  encounters: {},
  media: {},
  reviews: {},
}

export const api = isElectron ? window.api : {
  listProjects: async () => mock.projects,
  createProject: async (d) => { const p = { id: Date.now(), ...d, created_at: new Date().toISOString() }; mock.projects.push(p); return p },
  createSampleProject: async () => { const p = { id: Date.now(), name: '📘 Sample Tutorial Project', created_at: new Date().toISOString() }; mock.projects.push(p); return { id: p.id, tutorialReviewId: null, alreadyExisted: false } },
  getProject: async (id) => mock.projects.find(p => p.id == id) || null,
  updateProject: async () => true,
  deleteProject: async (id) => { mock.projects = mock.projects.filter(p => p.id != id); return true },
  listEncounters: async () => [],
  getEncounter: async () => null,
  createEncounter: async () => ({ id: Date.now() }),
  renameEncounter: async () => true,
  countEncounterReviews: async () => 0,
  deleteEncounter: async () => true,
  bulkDeleteEncounters: async () => ({ deleted: 0 }),
  batchCreateEncounters: async () => ({ created: 0 }),
  exportStructure: async () => null,
  previewImport: async () => null,
  applyImport: async () => ({ encountersCreated: 0, filesAdded: 0 }),
  createMediaFile: async () => ({ id: Date.now() }),
  listMediaFiles: async () => [],
  getMediaFile: async () => null,
  updateMediaType: async () => true,
  countMediaReviews: async () => 0,
  moveMediaFile: async () => true,
  renameMediaFile: async () => true,
  deleteMediaFile: async () => true,
  bulkDeleteMediaFiles: async () => ({ deleted: 0 }),
  bulkUpdateMediaType: async () => ({ updated: 0 }),
  getVideoUrl: async (p) => p,
  getMediaPlaybackInfo: async () => ({ status: 'not_linked', resolved_path: null, url: null, file_type: 'other' }),
  listReviews: async () => [],
  createReview: async (d) => ({ id: Date.now(), ...d, status: 'in_progress', created_at: new Date().toISOString() }),
  getReview: async () => null,
  submitReview: async () => true,
  unsubmitReview: async () => true,
  deleteReview: async () => true,
  restoreReview: async () => true,
  listDeletedReviews: async () => [],
  saveTimestamp: async (_, d) => Date.now(),
  deleteTimestamp: async () => true,
  updateTimestamp: async () => true,
  saveFormResponse: async () => true,
  saveMediaType: async () => Date.now(),
  listMediaTypes: async () => [],
  countMediaTypeReviews: async () => 0,
  deleteMediaType: async () => true,
  saveForm: async () => Date.now(),
  listForms: async () => [],
  getForm: async () => null,
  countFormResponses: async () => 0,
  deleteForm: async () => true,
  previewStructureMigration: async (_, data) => ({ kind: data?.kind, id: data?.id, scope: data?.scope || 'drafts', total: 0, drafts: 0, submitted: 0 }),
  migrateStructureReviews: async (_, data) => ({ kind: data?.kind, id: data?.id, scope: data?.scope || 'drafts', total: 0, drafts: 0, submitted: 0, updated: 0 }),
  listVersionHistory: async () => [],
  restoreVersion: async (_, data) => ({ kind: data?.kind, id: data?.id, restored_from_version: data?.version, current_version: data?.version }),
  saveInstruction: async () => Date.now(),
  listInstructions: async () => [],
  deleteInstruction: async () => true,
  uploadPdf: async () => null,
  getAppInfo: async () => ({ name: 'SDMo', version: '0.0.0-dev', packaged: false, platform: 'browser', arch: '' }),
  exportDiagnostics: async () => null,
  getUpdateStatus: async () => ({ state: 'unavailable', currentVersion: '0.0.0-dev', required: false, updateInfo: null }),
  checkForUpdates: async () => ({ state: 'unavailable', currentVersion: '0.0.0-dev', required: false, updateInfo: null }),
  downloadUpdate: async () => ({ state: 'unavailable', currentVersion: '0.0.0-dev', required: false, updateInfo: null }),
  installUpdate: async () => true,
  onUpdateStatus: () => 0,
  offUpdateStatus: () => {},
  getAppSettings: async () => ({ user_uuid: 'mock-uuid' }),
  setAppSettings: async () => ({}),
  getProjectName: async () => null,
  setProjectName: async () => true,
  setCloudFolderName: async () => true,
  getCloudFolderName: async () => null,
  getMachineReviewNames: async () => [],
  setOwnerPassword: async () => true,
  verifyOwnerPassword: async () => true,
  isProjectUnlocked: async () => true,
  lockProject: async () => true,
  syncNow: async () => ({ ok: true }),
  getSyncStatus: async () => ({ syncFolder: null, syncMode: 'none', syncFolderExists: false, cloudProvider: null, cloudFolderId: null, tokenExpired: false, lastSyncAt: null, hasPassword: false, isUnlocked: true }),
  selectSyncFolder: async () => null,
  saveProjectFile: async () => null,
  loadProjectFile: async () => null,
  importProjectAsNew: async () => ({ ok: true, projectId: null, syncHint: { mode: 'none', provider: null } }),
  joinFromLocalFolder: async () => ({ error: 'Not in Electron' }),
  joinFromCloudFolder: async () => ({ error: 'Not in Electron' }),
  exportExcel: async () => null,
  syncAcceptConfigUpdate: async () => ({ ok: true }),
  onConfigUpdateAvailable: () => 0,
  offConfigUpdateAvailable: () => {},
  onSyncConflict: () => 0,
  offSyncConflict: () => {},
  onSyncOffline: () => 0,
  offSyncOffline: () => {},
  onSyncOnline: () => 0,
  offSyncOnline: () => {},
  onGoogleDriveAccessRequired: () => 0,
  offGoogleDriveAccessRequired: () => {},
  onGoogleDriveMetadataMissing: () => 0,
  offGoogleDriveMetadataMissing: () => {},
  cloudConnectOneDrive: async () => ({ error: 'Not in Electron' }),
  cloudConnectGoogleDrive: async () => ({ error: 'Not in Electron' }),
  cloudPickGoogleDriveFolder: async () => ({ error: 'Not in Electron' }),
  cloudPickGoogleDriveFiles: async () => ({ error: 'Not in Electron' }),
  cloudDisconnect: async () => ({ ok: true }),
  cloudStatus: async () => ({ provider: null, connected: false }),
  cloudListFolders: async () => ({ ok: true, folders: [] }),
  cloudSelectFolder: async () => ({ ok: true }),
  cloudSyncNow: async () => ({ ok: true }),
  cloudCancelAuth: async () => ({ ok: true }),
  cloudResolveFolderLink: async () => ({ error: 'Not in Electron' }),
  fetchProjectStructure: async () => ({ ok: true }),
  checkManifest: async () => null,
  selectFolder: async () => null,
  scanMediaFolder: async () => ({ encountersAdded: 0, filesAdded: 0, directMediaFiles: 0, totalSubfolders: 0, stillUnlinked: 0, stillBroken: 0 }),
  mediaHealthCheck: async () => ({ unlinked: 0, broken: 0, ok: 0, notApplicable: 0, total: 0, hasBaseFolder: false, issues: [] }),
  getBaseFolder: async () => null,
  setBaseFolder: async () => true,
  autolink: async () => ({ linked: 0, skipped: 0, ambiguous: 0, notFound: 0 }),
  setMediaLink: async () => true,
  markMediaNotApplicable: async () => true,
  clearMediaLink: async () => true,
  browseMediaFile: async () => null,
  openWorkspaceWindow: async () => null,
  closeWorkspaceWindow: async () => null,
  notifyReviewUpdate: async () => null,
  isFullscreen: async () => false,
  setFullscreen: async () => {},
  onReviewUpdated: () => 0,
  offReviewUpdated: () => {},
  onWorkspaceClosed: () => 0,
  offWorkspaceClosed: () => {},
}

export function formatTime(seconds) {
  if (seconds == null || isNaN(seconds)) return '0:00'
  const m = Math.floor(seconds / 60)
  const s = Math.floor(seconds % 60)
  return `${m}:${s.toString().padStart(2, '0')}`
}

export function formatDate(iso) {
  if (!iso) return ''
  return new Date(iso).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
}
